// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: tokenverifier.proto

package tokenverifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenVerifierClient is the client API for TokenVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenVerifierClient interface {
	VerifyToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyReply, error)
}

type tokenVerifierClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenVerifierClient(cc grpc.ClientConnInterface) TokenVerifierClient {
	return &tokenVerifierClient{cc}
}

func (c *tokenVerifierClient) VerifyToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyReply, error) {
	out := new(VerifyReply)
	err := c.cc.Invoke(ctx, "/tokenverifier.TokenVerifier/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenVerifierServer is the server API for TokenVerifier service.
// All implementations must embed UnimplementedTokenVerifierServer
// for forward compatibility
type TokenVerifierServer interface {
	VerifyToken(context.Context, *VerifyRequest) (*VerifyReply, error)
	mustEmbedUnimplementedTokenVerifierServer()
}

// UnimplementedTokenVerifierServer must be embedded to have forward compatible implementations.
type UnimplementedTokenVerifierServer struct {
}

func (UnimplementedTokenVerifierServer) VerifyToken(context.Context, *VerifyRequest) (*VerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedTokenVerifierServer) mustEmbedUnimplementedTokenVerifierServer() {}

// UnsafeTokenVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenVerifierServer will
// result in compilation errors.
type UnsafeTokenVerifierServer interface {
	mustEmbedUnimplementedTokenVerifierServer()
}

func RegisterTokenVerifierServer(s grpc.ServiceRegistrar, srv TokenVerifierServer) {
	s.RegisterService(&TokenVerifier_ServiceDesc, srv)
}

func _TokenVerifier_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenVerifierServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenverifier.TokenVerifier/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenVerifierServer).VerifyToken(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenVerifier_ServiceDesc is the grpc.ServiceDesc for TokenVerifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenVerifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenverifier.TokenVerifier",
	HandlerType: (*TokenVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _TokenVerifier_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokenverifier.proto",
}
